### ISSUE TITLE
Adding OMSCSNotes to your README

### ISSUE THREAD

**Issue by m4ttsch** [pyjarrett/OMSCS_Survival_Guide#4]
Hey there!

I own and develop a site called [OMSCSNotes](https://www.omscs-notes.com/) where I share all of my lecture notes for the classes I have taken in OMSCS. So far, I have content for GIOS, IIS, CN, ML4T, and Simulation. By the end of the program, I will likely add ML, RL, GA, AI, and one other.

Since I built the site in mid-2019, I've had 27,000 users visit the site and just shy of 250,000 page views. People tell me they love it, and I think it's a great resource. Can we add it to your README for more visibility?

Thanks,
Matt Schlenker

**Comment by jimlohse** [comment]
Hey I'm a head TA for CN and we use different content now, I'll look at your notes and see if they would be good for students who need to brush up on basic networking concepts.

I assume you don't have any plans to update the notes for our new content?

**Comment by m4ttsch** [comment]
I don't have time to update my notes to the new content, correct. I was asking more about you adding my notes to your general survival guide than sharing them specifically with your CN students. Let me know what works!

**Comment by clbx** [comment]
+1 for adding a link to MattsNotes. They were extremely helpful for IIS, a class commonly taken by first semester students

**Comment by m4ttsch** [comment]
Thank you for the kind words!

**Comment by pyjarrett** [comment]
I don't want to give endorsements to any paid content, especially when it isn't being updated.  I've left this repository up because current students and alumni have the opportunity to make corrections and edits to keep the information up to date.  There doesn't seem to be much interest in doing this, so this repo might be taken down in the future.

**Comment by clbx** [comment]
The content is not paid, only the PDFs.

Don’t close the repository, I have a few updates locally to push up soon.

**Comment by m4ttsch** [comment]
@pyjarrett Why would you close something that takes no effort to keep open and that, given 100+ stars, is clearly a valuable resource to many people?
